### ISSUE TITLE
User of service should be able to give shacl-shapes as input.

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dcat-ap-no-validator-service#31]

**Comment by jimjyang** [comment]
👍

**Comment by jimjyang** [comment]
Bør støtte følgende måter: 
1. Som fil(er)
2. Som URL(er)

Kan prioriteres lavere (selv om det ikke bør gi store utslag i utviklingskostnad, regner jeg med): Støtte for filer og URLer (i flertall) fordi det kan være flere shacl-filer som til sammen spesifiserer valideringsregler for samme spesifikasjon. EU bruker f.eks. to ulike shacl-filer for samme standard, den ene kun for å sjekke bruk av kontrollerte vokabularer. Validatoren vår bør derfor kunne importere og slå sammen shacl-shapes fra flere filer/kilder.
