### ISSUE TITLE
Validate turtle

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/dcat-ap-no-validator-service#35]
Implement a turtle validator layer (ex https://github.com/IDLabResearch/TurtleValidator) before validating with shacl-shapes.

**Comment by jeffreiffers** [comment]
Per i dag så sier vi ingenting om hva slags format tekst verdien skal ha. Hvis vi kun skal støtte turtle så kan vi enkelt legge til en syntax validering. Men hvis vi skal støtte flere formater trenger vi å kunne velge eller må vi lage noe automatikk for å gjenkjenne formatet.

**Comment by shenluna** [comment]
Lukker saken da dette ikke vil bli prioritert nå.
