### ISSUE TITLE
Subklasse-problematikk

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dcat-ap-no-validator-service#36]
Det blir i dag valideringsfeil hvis objektet i en trippel er en instans av en subklasse av den lovlige klassen ("lovlig" vil si direkte angitt i shacl-filen). 

Validatoren bør resonnere seg frem til at dette er et lovlig objekt ved f.eks. å bruke "klasse-hierarkiet" spesifisert i den "bakforliggende" ontologien.

**Comment by stigbd** [comment]
Vil bli realisert ved #37
