### ISSUE TITLE
The validator stops at `vcard:hasEmail <mailto:examples@examples.com>`

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dcat-ap-no-validator-service#38]
When I include (optional) 

`  dcat:contactPoint [ a  vcard:Organization ; # kontaktpunkt
    vcard:hasEmail <mailto:examples@examples.com> ;
    ] ;`

I get `{"detail": "No connection adapters were found for 'mailto:examples@examples.com'"}` from the validator, as a kind of syntax error (the validator stops).

**Comment by stigbd** [comment]
Great if you could paste your input config (if any) when you call the service.

**Comment by jimjyang** [comment]
> Great if you could paste your input config (if any) when you call the service.

If I understand you correctly, none input config used (except specifying which data file and which shacl file).

**Comment by stigbd** [comment]
This issue should be fixed in c892270e756b0eca15c14668cc4c9cb840cbcf62. Please retest and verfiy, @shenluna and @jimjyang

**Comment by jimjyang** [comment]
> This issue should be fixed in [c892270](https://github.com/Informasjonsforvaltning/dcat-ap-no-validator-service/commit/c892270e756b0eca15c14668cc4c9cb840cbcf62). Please retest and verfiy, @shenluna and @jimjyang

Tested the staging version and it works fine!

**Comment by shenluna** [comment]
Tested in staging and verified in prod. Works fine!
