### ISSUE TITLE
Optimalisere logging.debug

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dcat-ap-no-validator-service#39]
Det jeg mente var egentlig noe som dette 

```
if logging.isEnabledFor(logging.DEBUG):
    logging.debug("Message with %s, %s", expensive_func1(), expensive_func2())
```
                                       
Man sparer cpu ved å ikke kalle logging.debug. Enklest er å lage en wrapper metode som erstatter logging.debug().

_Originally posted by @jeffreiffers in https://github.com/Informasjonsforvaltning/dcat-ap-no-validator-service/pull/34#discussion_r576189775_

**Comment by KjerstiSteien** [comment]
@jeffreiffers @valosnah er dette fortsatt relevant å gjøre noe med?

**Comment by jeffreiffers** [comment]
> @jeffreiffers @valosnah er dette fortsatt relevant å gjøre noe med? 

Nei synes ikke
