### ISSUE TITLE
Feilmelding 'Could not connect to ....'

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/dcat-ap-no-validator-service#41]
Avhengig av hvilken måte man velger å validere får man i staging feilmeldingen 'Could not connect to None' eller 'Could not connect to *url*'

Eksempel ved fil opplasting:
![image](https://user-images.githubusercontent.com/73637969/108082071-f80aba00-7071-11eb-9303-dfc469242c7b.png)

Eksempel med tekst:
![image](https://user-images.githubusercontent.com/73637969/108082226-26889500-7072-11eb-9627-caabde4663a3.png)

Eksempel med URL:
![image](https://user-images.githubusercontent.com/73637969/108082375-5041bc00-7072-11eb-85ad-c934483d9678.png)

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/6e4b5728-8d3a-4327-9c78-19a606312ec9)

**Comment by stigbd** [comment]
Had to fix errorhandling when referencing remote graphs that does not exist. Resolved in 83b5b14
