### ISSUE TITLE
Loggnivå vises ikke korrekt i GCP

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/dcat-ap-no-validator-service#44]
All logging som ikke er requests, tolkes som error.

Som standard tolker GCP python-logging veldig enkelt; stdout = info, stderr = error.
For å få riktig nivå, anbefales det å formatere loggene som JSON

![image](https://user-images.githubusercontent.com/8625716/108709518-190c5880-7513-11eb-99b3-de7559f03440.png)

![image](https://user-images.githubusercontent.com/8625716/108710213-0cd4cb00-7514-11eb-805c-65c826dd2574.png)

**Comment by stigbd** [comment]
Eg meiner å ha sett at @NilsOveTen har laga ei løysing for dette i anna python-repo. Kan noko evt dele lenke til dette her?

**Comment by valosnah** [comment]
@stigbd https://github.com/Informasjonsforvaltning/altinn-model-publisher/pull/46
