### ISSUE TITLE
Validering på shacl-regler

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/dcat-ap-no-validator-service#50]
Når man prøver å validere shacl-regler f.eks https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no/v1.1/shacl/dcat-ap_shacl_shapes_1.1.ttl

Avhengig av hvilken regelgraf man velger får man forskjellig tilbake melding, den ene gir 'Network error' og den andre oversiktsbilde med feil, uten feil.

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/638c7f8d-efbf-46bf-83d0-8083410775a5)
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/f527410d-ba73-4395-8b8f-1cfba899cf8e)

**Comment by stigbd** [comment]
Når eg tester lokalt, fungerer dette greit, men tar lang tid. Mistenker duplicat av https://github.com/Informasjonsforvaltning/dcat-ap-no-validator-gui/issues/29

Lukker derfor.
