### ISSUE TITLE
Får statuskode 500 ved validering av filer som ikke kan valideres

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/dcat-ap-no-validator-service#51]
Ved validering på filer som ikke kan valideres (pdf f.eks) får man feilmeldingen: Noe gikk galt. Vennligst prøv igjen senere.

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/964805bf-5613-402f-860c-03d594e13ff4)

**Comment by stigbd** [comment]
Fiksa i 0d0b5647fb435ff5b2aa468aea7c43e8f8a211e0

**Comment by shenluna** [comment]
Testet i staging
Får nå statuskode 400
![image](https://user-images.githubusercontent.com/73637969/110331992-13893500-8020-11eb-89fb-9aa98fe4b4e5.png)
