### ISSUE TITLE
CORS blir ikke håndtert så derfor viser vi network error

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dcat-ap-no-validator-service#54]
curl -v -F data-graph-url=https://dataut.vegvesen.no/catalog.ttl -F shapes-graph-url=https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no/v2/shacl/DCAT-AP-NO-shacl_shapes_2.00.ttl -F config='{"expand":true,"includeExpandedTriples":false}}' -X POST https://validator.fellesdatakatalog.digdir.no/validator
Denne gir 500 feil.

Kan vi fikse dette?

**Comment by stigbd** [comment]
Du har ein feil i curl-kommandoen. Fjern den siste siste `}` i config-part. (Det er forøvrig ikkje nødvendig å legge ved config når du ber om default.
