### ISSUE TITLE
Uforklarlig valideringsfeil

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dcat-ap-no-validator-service#75]
Ved å validere denne testfila fra Direktoratet for e-helse, https://github.com/Directorate-for-E-Health/Metadata-Felles-datakatalog/blob/main/test_rdf_to_fdk.txt, får jeg følgende feil som jeg ikke kan se hvorfor: 

![image](https://user-images.githubusercontent.com/46558821/141069069-e36743a8-c928-4cda-9c39-45768a0969de.png)

Jeg kan ikke se bruk av "licence" i testfila. Dessuten får jeg ikke denne feilen når jeg bruker Curl mot validatoren.

**Comment by stigbd** [comment]
Min curl gir den same valideringsfeilen når eg køyrer standard-konfigurasjon (`expand=True, "includeExpandedTriples": false`):

```
% curl -i \  
 -H "Accept: text/turtle" \
 -H "Content-Type: multipart/form-data" \
 -F "data-graph-url=https://raw.githubusercontent.com/Directorate-for-E-Health/Metadata-Felles-datakatalog/main/test_rdf_to_fdk.txt" \
 -F "shapes-graph-url=https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no/v2/shacl/DCAT-AP-NO-shacl_shapes_2.00.ttl" \
 -F "ontology-graph-url=https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no/develop/shacl/ontologies.ttl" \
 -X POST https://validator.fellesdatakatalog.digdir.no/validator
```
Feilen er:
```
[ a ns1:ValidationResult ;
            ns1:focusNode <http://publications.europa.eu/resource/authority/licence> ;
            ns1:resultMessage "Less than 1 values on <http://publications.europa.eu/resource/authority/licence>->dct:title" ;
            ns1:resultPath ns2:title ;
            ns1:resultSeverity ns1:Violation ;
            ns1:sourceConstraintComponent ns1:MinCountConstraintComponent ;
            ns1:sourceShape [ ns1:minCount 1 ;
                    ns1:nodeKind ns1:Literal ;
                    ns1:path ns2:title ;
                    ns1:severity ns1:Violation ] ],
```
Og går på at http://publications.europa.eu/resource/authority/licence angiveleg ikkje har dct:title. Denne feilen vil også dukke opp når ein validerer _utan_ ekspansjon, sidan dette gjelder ontologien som er bruk av validator.

Men når vi sjekker http://publications.europa.eu/resource/authority/licence, ser at vi den _faktisk_ har dct:title. Derfor landar eg på at validatoren bruker ein cachet versjon av license-vokabularet, der dct:title _ikkje_ var brukt.

Eg skal forsøke å friske opp cachen.
Men eg meiner å hugse at vi har meldt den feilen til EU (at dei bruker skos:prefLabel i staden for dct:title på vokabularer).

**Comment by jimjyang** [comment]
Ang. EU-vocab generelt: Publications Office holder på å føye til dct:title, https://github.com/SEMICeu/DCAT-AP/issues/192#issuecomment-909259250.

**Comment by stigbd** [comment]
Eg kan bekrefte at når eg køyrer validator lokalt, utan bruk av cache, blir feilen ikkje rapportert. Hypotesen om at det er gammal cachet versjon av ontologien som blir brukt, er corroborated.

Imidlertid ser eg at tjenesten _aldri_ skal bruke cache for ontologier, så her er det ganske enkelt ein bug i koden.

Takk for at du spotta den, @jimjyang !

**Comment by stigbd** [comment]
@jimjyang Eg har retta feilen og deploya ny versjon av tjeneste, samt tømt cache, i staging-miljø. Kan du vere snill å verifisere der før eg prodsetter?
Lenke: https://staging.fellesdatakatalog.digdir.no/validator

**Comment by stigbd** [comment]
t.o. eg har konfigurert cache til å ta vare på verdier i eitt døgn. Tenker at feks eu ikkje oppdaterer oftare enn det.

**Comment by jimjyang** [comment]
> @jimjyang Eg har retta feilen og deploya ny versjon av tjeneste, samt tømt cache, i staging-miljø. Kan du vere snill å verifisere der før eg prodsetter? Lenke: https://staging.fellesdatakatalog.digdir.no/validator

Testet mot staging og valideringsfeilen kommer ikke opp nå, dvs. OK nå 👍.

**Comment by stigbd** [comment]
Bekrefter at fiksen er i prod.
